/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica2;

import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFormattedTextField;
import javax.swing.JFormattedTextField.AbstractFormatter;
import javax.swing.JFormattedTextField.AbstractFormatterFactory;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.DocumentFilter;
import javax.swing.text.InternationalFormatter;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author santa
 */
public class practica_2 extends javax.swing.JFrame {

    /**
     * Creates new form practica_2
     */
    public practica_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        upperPanel = new javax.swing.JPanel();
        amountInputPanel = new javax.swing.JPanel();
        amountInputField = new javax.swing.JFormattedTextField();
        ratioInputPanel = new javax.swing.JPanel();
        ratioInputField = new javax.swing.JFormattedTextField();
        lowerPanel = new javax.swing.JPanel();
        convertButton = new javax.swing.JButton();
        rightResultPanel = new javax.swing.JPanel();
        rightResultField = new javax.swing.JTextField();
        leftResultPanel = new javax.swing.JPanel();
        leftResultField = new javax.swing.JTextField();
        convertButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        upperPanel.setPreferredSize(new java.awt.Dimension(380, 100));

        amountInputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad\n"));
        amountInputPanel.setPreferredSize(new java.awt.Dimension(350, 64));

        amountInputField.setFormatterFactory(new AbstractFormatterFactory() {

            @Override
            public AbstractFormatter getFormatter(JFormattedTextField tf) {
                NumberFormat format = DecimalFormat.getInstance();
                format.setMinimumFractionDigits(2);
                format.setMaximumFractionDigits(2);
                format.setRoundingMode(RoundingMode.HALF_UP);
                InternationalFormatter formatter = new InternationalFormatter(format);
                formatter.setAllowsInvalid(false);
                formatter.setMinimum(0.0);
                formatter.setMaximum(10000.0);
                return formatter;
            }
        });

        javax.swing.GroupLayout amountInputPanelLayout = new javax.swing.GroupLayout(amountInputPanel);
        amountInputPanel.setLayout(amountInputPanelLayout);
        amountInputPanelLayout.setHorizontalGroup(
            amountInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(amountInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );
        amountInputPanelLayout.setVerticalGroup(
            amountInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(amountInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        ratioInputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tasa de Cambio (EUR -> USD)"));

        ratioInputField.setFormatterFactory(new AbstractFormatterFactory() {

            @Override
            public AbstractFormatter getFormatter(JFormattedTextField tf) {
                NumberFormat format = DecimalFormat.getInstance();
                format.setMinimumFractionDigits(2);
                format.setMaximumFractionDigits(2);
                format.setRoundingMode(RoundingMode.HALF_UP);
                InternationalFormatter formatter = new InternationalFormatter(format);
                formatter.setAllowsInvalid(false);
                formatter.setMinimum(0.0);
                formatter.setMaximum(10000.0);
                return formatter;
            }
        });

        javax.swing.GroupLayout ratioInputPanelLayout = new javax.swing.GroupLayout(ratioInputPanel);
        ratioInputPanel.setLayout(ratioInputPanelLayout);
        ratioInputPanelLayout.setHorizontalGroup(
            ratioInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ratioInputField)
        );
        ratioInputPanelLayout.setVerticalGroup(
            ratioInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ratioInputField)
        );

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addComponent(amountInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ratioInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(amountInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ratioInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        convertButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        convertButton.setText(">>");
        convertButton.setAlignmentX(0.5F);
        convertButton.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        convertButton.setDefaultCapable(false);
        convertButton.setMaximumSize(new java.awt.Dimension(58, 58));
        convertButton.setMinimumSize(new java.awt.Dimension(58, 58));
        convertButton.setPreferredSize(new java.awt.Dimension(60, 60));
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        rightResultPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Dolares"));
        rightResultPanel.setPreferredSize(new java.awt.Dimension(320, 64));

        rightResultField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rightResultField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rightResultField.setEnabled(false);

        javax.swing.GroupLayout rightResultPanelLayout = new javax.swing.GroupLayout(rightResultPanel);
        rightResultPanel.setLayout(rightResultPanelLayout);
        rightResultPanelLayout.setHorizontalGroup(
            rightResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightResultField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );
        rightResultPanelLayout.setVerticalGroup(
            rightResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightResultField)
        );

        leftResultPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Euros"));
        leftResultPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        leftResultPanel.setPreferredSize(new java.awt.Dimension(320, 64));

        leftResultField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        leftResultField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        leftResultField.setEnabled(false);

        javax.swing.GroupLayout leftResultPanelLayout = new javax.swing.GroupLayout(leftResultPanel);
        leftResultPanel.setLayout(leftResultPanelLayout);
        leftResultPanelLayout.setHorizontalGroup(
            leftResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftResultField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        leftResultPanelLayout.setVerticalGroup(
            leftResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftResultField, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        convertButton2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        convertButton2.setText("<<");
        convertButton2.setAlignmentX(0.5F);
        convertButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        convertButton2.setDefaultCapable(false);
        convertButton2.setMaximumSize(new java.awt.Dimension(58, 58));
        convertButton2.setMinimumSize(new java.awt.Dimension(58, 58));
        convertButton2.setPreferredSize(new java.awt.Dimension(60, 60));
        convertButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lowerPanelLayout = new javax.swing.GroupLayout(lowerPanel);
        lowerPanel.setLayout(lowerPanelLayout);
        lowerPanelLayout.setHorizontalGroup(
            lowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lowerPanelLayout.createSequentialGroup()
                .addComponent(leftResultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(convertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convertButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightResultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        lowerPanelLayout.setVerticalGroup(
            lowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lowerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(lowerPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(convertButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rightResultPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lowerPanelLayout.createSequentialGroup()
                        .addGroup(lowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(leftResultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(convertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lowerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(upperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lowerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        /**
         * Sequence
         * 
         * Set conversion variable to "true"
         * Check whether text on both ratio and amount fields fulfills its correct format
         * Parse each parameter into a double value using Double class
         * Update both result fields
         */
        eurosToDollars();
    }//GEN-LAST:event_convertButtonActionPerformed

    private void convertButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButton2ActionPerformed
        dollarsToEuros();
    }//GEN-LAST:event_convertButton2ActionPerformed

    
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(practica_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(practica_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(practica_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(practica_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new practica_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField amountInputField;
    private javax.swing.JPanel amountInputPanel;
    private javax.swing.JButton convertButton;
    private javax.swing.JButton convertButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField leftResultField;
    private javax.swing.JPanel leftResultPanel;
    private javax.swing.JPanel lowerPanel;
    private javax.swing.JFormattedTextField ratioInputField;
    private javax.swing.JPanel ratioInputPanel;
    private javax.swing.JTextField rightResultField;
    private javax.swing.JPanel rightResultPanel;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables
    private boolean status = false;

    private void dollarsToEuros() {
        this.rightResultField.setText(this.amountInputField.getText());
        String strAmount = this.formatToDouble(this.amountInputField.getText());
        String strRatio = this.formatToDouble(this.ratioInputField.getText());
        double amount = (strAmount.equals("")) ? 0.00 : Double.parseDouble(strAmount);
        double ratio = (strRatio.equals("")) ? 0.00 : Double.parseDouble(strRatio);
        double result = (ratio == 0.00) ? 0.00 : amount*(1/ratio);
        this.leftResultField.setText(String.format("%,.2f", result));
    }

    private void eurosToDollars() {
        this.leftResultField.setText(this.amountInputField.getText());
        String strAmount = this.formatToDouble(this.amountInputField.getText());
        String strRatio = this.formatToDouble(this.ratioInputField.getText());
        double amount = (strAmount.equals("")) ? 0.00 : Double.parseDouble(strAmount);
        double ratio = (strRatio.equals("")) ? 0.00 : Double.parseDouble(strRatio);
        double result = amount*ratio;
        this.rightResultField.setText(String.format("%,.2f", result));
    }
    
    private String formatToDouble(String number){
        String res = number.replace(".", ":");
        res = res.replace(",", ".");
        res = res.replace(":", "");
        return res;
    }
}
